### ISSUE TITLE
No longer working ?

### ISSUE THREAD

**Issue by cburkins** [AdamNaj/ZWaveGraphHA#10]
Recently upgraded from 0.116 to 2020.12.7.    Seems to no longer be working.  Bummed, as I really like this feature.   Any logs that I can provide to help troubleshoot this ?  Also upgraded to Home Assistant OS 5.8.  

Panel seems to show my two Z-Wave devices as "Unconnected".   Strange, as I can still operate those Z-Wave devices just fine.

![image](https://user-images.githubusercontent.com/9342308/102723736-21100800-42d8-11eb-87ed-5924b1cc718b.png)

**Comment by MikeTheCleric** [comment]
Hi! I've got the same problem. After the latest version of HA (2020.12.7) all mi nodes are labelled as "unconnected".

**Comment by psarossy** [comment]
Same here on 2020.12.1: 
![image](https://user-images.githubusercontent.com/207358/102849559-653cfe80-43e5-11eb-9a17-026dac8699ff.png)

Just started building a new network, the first node shows up as expected, but all later nodes show "unconnected"

**Comment by psarossy** [comment]
Actually after a hard power reset (moved the Pi to an SSD), the graph updated and seems to work
![image](https://user-images.githubusercontent.com/207358/103042726-94b84c00-4548-11eb-8aed-939a30f07056.png)

But adding new nodes do not register as connected:![image](https://user-images.githubusercontent.com/207358/103044023-f5498800-454c-11eb-849e-61e348978e8b.jpeg)


It seems after network heals and reloads it also regenerates, but not on the fly.

**Comment by aderusha** [comment]
I'm in the same boat here, restarting doesn't appear to do anything.  ZWave is working fine, but more than half of my devices are showing disconnected.  Running stock OZW integration, and this was a previously-working install of zwavegraph3.js v3.2.

![https://i.imgur.com/9VzwcBc.png](https://i.imgur.com/9VzwcBc.png)

**Comment by cburkins** [comment]
@AdamNaj Wondering if you could have a quick look at this.   I think your Z-Wave Graph plugin is popular and needed ! :). Looks like a few of us are having a similar problem.   If you need any detail about our configs, please just ask.

**Comment by PrplHaz4** [comment]
It looks like the cause of this issue is that the Neighbors property on certain nodes is not being populated correctly.  Not sure why that is happening, however....and, with the new zwave-js integration on the horizon, not sure how much attention this will get to be fixed.

It does not look like a problem with this component though, as if there are no neighbors, how will it know what to draw?  Sounds like it's time to start poking around the related libraries to see if there's an issue for this open yet.

Edit to add: Refreshing the node in Zwave config seems to restore the Neighbors, and fix the graph for that node.

Working Node:
![image](https://user-images.githubusercontent.com/841414/106023279-a71c2d00-6094-11eb-8862-be51da0e5cac.png)

Broken Node (note it's missing the "Neighbors" property):
![image](https://user-images.githubusercontent.com/841414/106023614-f3676d00-6094-11eb-9765-fc6d2ec6bc4c.png)

**Comment by AdamNaj** [comment]
This repository is archived as this exact graph was included as part of the [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt).
If you are using the [ZwaveJS](https://github.com/zwave-js/node-zwave-js), please upgrade to full [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt) to get this functionality back.
