### ISSUE TITLE
Not working on OpenZwave ??

### ISSUE THREAD

**Issue by szibis** [AdamNaj/ZWaveGraphHA#8]
I have this error:
```
Logger: homeassistant.components.websocket_api.http.connection.1743651768
Source: components/websocket_api/connection.py:84
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 17:51:08 (1 occurrences)
Last logged: 17:51:08

Received invalid command: zwave/network_status
```

And screen look like this

![image](https://user-images.githubusercontent.com/329831/95885144-38cd8c00-0d7d-11eb-9e0d-581b47e346fe.png)

Like skeleton is rendered but without anything from zwave as the network status command failed and using openzwave (beta) on Home Assistant 0.116.2.

**Comment by embcla** [comment]
Hi @szibis , how and where did you get those logs? I have the same screen, but could never find the source of the issue

**Comment by AdamNaj** [comment]
This panel is currently working only on the old ZWave implementation. Unfortunately, I didn't have the time to migrate yet. Any pointers at some tutorials for the migration would be useful though :)

**Comment by Nixon506E** [comment]
https://github.com/abmantis/ozw-network-visualization-card

https://community.home-assistant.io/t/how-to-test-the-ozw-beta-without-fully-switching-over/211282

**Comment by jef-pearlman** [comment]
FWIW, I've got this mostly functional with a fairly ugly AppDaemon app that subscribes to the MQTT topics that contain the ozw node information and creates fake zwave.* nodes on the fly.  The visualization then acts as normal using the fake zwave.* nodes.  Some of the information used isn't actually present in MQTT--primarily, an associated entity id, the related entity state, and its friendly name.  Right now I'm using the unpleasant workaround of scanning the entities list for one with a "node_id" attribute that matches the node number and just taking the first match I find to be the right entity.  It often is!  And sometimes is not.  ;)  Finally, some of the stats data is in a different MQTT topic, and for the moment I don't bother with that, though it should be straightforward to do.

As far as I can tell the zwave node information is not otherwise available programmatically.  Is there any way to access MQTT from your code without a massive rewrite?  If so, it would be fairly straightforward from there to pull that data, and shouldn't be too hard to keep the code working with the old structure at the same time.  Dealing with the entity-related data might still be a bit messy.

The relevant MQTT topic is `OpenZWave/(instance)/node/(node_id)/` so `OpenZWave/1/node/1/` would be the master controller for most people.

BTW, if someone could post some example zwave.* states, I'd love to use that to improve it; I'm kind of guessing what's supposed to be in the attributes based on how the js uses it and some similar naming between the identifiers in the two versions.

Let me know if there's any way I can help.  Thanks for a very useful tool!

**Comment by AdamNaj** [comment]
This repository is archived as this exact graph was included as part of the [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt).
If you are using the [ZwaveJS](https://github.com/zwave-js/node-zwave-js), please upgrade to full [Zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt) to get this functionality back.
